[package]
org = "ballerina"
name = "mcp_shopping_server"
version = "0.1.0"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mcp"
version = "1.0.0"
repository = "local"
