[package]
org = "ballerina"
name = "mcp_shopping_client"
version = "0.1.0"
distribution = "2201.12.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerina"
name = "mcp"
version = "0.9.4"
repository = "local"
