[package]
org = "ballerina"
name = "mcp"
version = "1.0.0"
authors = ["Ballerina"]
keywords = ["mcp"]
repository = "https://github.com/ballerina-platform/module-ballerina-mcp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.12.0"

[platform.java21]
graalvmCompatible = true

[[platform.java21.dependency]]
groupId = "io.ballerina.stdlib."
artifactId = "mcp-native"
version = "1.0.0"
path = "../native/build/libs/mcp-native-1.0.0.jar"
